on:
  push:
    branches:
    - "feature/*"
    - "post/*"
    - "hotfix/*"
    - "bugfix/*"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: pull-request
      uses: repo-sync/pull-request@v2.6
      with:
        source_branch: ""                                 # If blank, default: triggered branch
        destination_branch: "main"                      # If blank, default: master
        pr_title: "Pulling ${{ github.ref }} into main" # Title of pull request
        # pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
        pr_reviewer: "wanted2"                         # Comma-separated list (no spaces)
        pr_assignee: "wanted2"                         # Comma-separated list (no spaces)
        pr_label: "auto-pr,auto-merge"                               # Comma-separated list (no spaces)
        # pr_milestone: "Milestone 1"                       # Milestone name
        pr_draft: false                                    # Creates pull request as draft
        pr_allow_empty: false                              # Creates pull request even if there are no changes
        github_token: ${{ secrets.GITHUB_TOKEN }}